IMAGE_INSTALL_append = " peekpoke"
IMAGE_INSTALL_append = " gpio-demo"
IMAGE_INSTALL_append = " libiio"
IMAGE_INSTALL_append = " libiio-iiod"
IMAGE_INSTALL_append = " libad9361-iio"
IMAGE_INSTALL_append = " wpa-supplicant_2.5"
IMAGE_INSTALL_append = " iw_4.7"
IMAGE_INSTALL_append = " custom-files"
